apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockmate
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockmate
  template:
    metadata:
      labels:
        app: dockmate
    spec:
      containers:
      # - name: dockmate
      #   image: kejr03/dockmate:latest
      #   ports:
      #   - containerPort: 5000
      - name: dockmate
        image: dockmate:local  
        imagePullPolicy: Never  
