name: Build, Test and Deploy Docker Image

on:
  pull_request:
    branches:
      - master
      - final
  push:
    branches:
      - master
      - final

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3  

    - name: Log in to Docker Hub
      uses: docker/login-action@v3  
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: docker build -t kejr03/dockmate:latest .

    - name: Run tests inside container
      run: |
        docker run -d --name app-test -p 5000:5000 kejr03/dockmate:latest
        sleep 5
        docker exec app-test pytest app/test_app.py
        docker stop app-test
        docker rm app-test

    - name: Push Docker image to Docker Hub
      if: ${{ success() }}  # Correct syntax for condition
      run: docker push kejr03/dockmate:latest
